# Generated by Django 2.1.9 on 2019-11-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nsdmsubscriptionmodel',
            name='notificationTypes',
        ),
        migrations.RemoveField(
            model_name='nsdmsubscriptionmodel',
            name='subscriptionid',
        ),
        migrations.AddField(
            model_name='nsdmsubscriptionmodel',
            name='notification_types',
            field=models.TextField(db_column='NOTIFICATION_TYPES', null=True),
        ),
        migrations.AddField(
            model_name='nsdmsubscriptionmodel',
            name='subscription_id',
            field=models.CharField(db_column='SUBSCRIPTION_ID', default='SOME STRING', max_length=255, primary_key=True, serialize=False),
        ),
    ]
